config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: "users/sessions",
               registrations: "users/registrations",
               omniauth_callbacks: "users/omniauth_callbacks"
             }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "homes#index"
  resource :wallet, only: [:show], path: "/:url" do
    resources :moji_trades, only: %i[index create], path: "/moji"
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  def show
    @wallet = Wallet.find_by(url: params[:url])
    wallet_user = @wallet.user_id
    user = User.find_by(id: wallet_user)
    @profile = user.profile

    # redirect_to "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=#{ENV["STRIPE_CLIENT_ID"]}&stripe_user[email]=#{current_user.email}&stripe_user[url]=http://localhost:3000/#{@wallet.url}&scope=read_write",
    #             allow_other_host: true
  end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/show.html.erb
<link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
<link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">
<section class="pt-16 bg-blueGray-50">
  <div class="w-full lg:w-4/12 px-4 mx-auto">
    <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg mt-16">
      <div class="px-6">
        <div class="flex flex-wrap justify-center">
          <div class="w-full px-4 flex justify-center">
            <div class="relative">
              <img alt="..." src="https://images.unsplash.com/photo-1493752603190-08d8b5d1781d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80" class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16 max-w-150-px">
            </div>
          </div>
          <div class="w-full px-4 text-center mt-20">
            <div class="flex justify-center py-4 lg:pt-4 pt-8">
              <div class="mr-4 p-3 text-center">
                <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                  <%=@wallet.plus%>
                </span>
                <span class="text-sm text-blueGray-400">plus</span>
              </div>
              <div class="mr-4 p-3 text-center">
                <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                  <%=@wallet.minus%>
                </span>
                <span class="text-sm text-blueGray-400">minus</span>
              </div>
              <div class="lg:mr-4 p-3 text-center">
                <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                  <%=@wallet.plus - @wallet.minus%>
                </span>
                <span class="text-sm text-blueGray-400">total</span>
              </div>
            </div>
          </div>
        </div>
        <div class="text-center mt-12">
          <h3 class="text-xl font-semibold leading-normal mb-2 text-blueGray-700">
            <%= @wallet.url  %>
          </h3>
          <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
            <i class="fas fa-map-marker-alt mr-2 text-lg text-blueGray-400"></i>
            Tokyo, JP
          </div>
          <div class="mb-2 text-blueGray-600 mt-10">
            <i class="fas fa-briefcase mr-2 text-lg text-blueGray-400"></i>
            Lorem ipsum dolor sit amet
          </div>
          <div class="mb-2 text-blueGray-600">
            <i class="fas fa-university mr-2 text-lg text-blueGray-400"></i>
            Lorem ipsum dolor sit amet
          </div>
        </div>
        <div class="mt-10 py-10 border-t border-blueGray-200 text-center">
          <div class="flex flex-wrap justify-center">
            <div class="w-full lg:w-9/12 px-4">
              <p class="mb-4 text-lg leading-relaxed text-blueGray-700">
                <%= @profile.introduction  %>
              </p>
              <%= link_to wallet_trades_path, class: 'font-normal text-pink-500' do %>
                MOJIを送る
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer class="relative  pt-8 pb-6 mt-8">
    <div class="container mx-auto px-4">
      <div class="flex flex-wrap items-center md:justify-between justify-center">
        <div class="w-full md:w-6/12 px-4 mx-auto text-center">
          <div class="text-sm text-blueGray-500 font-semibold py-1">
            Made with <a href="https://www.creative-tim.com/product/notus-js" class="text-blueGray-500 hover:text-gray-800" target="_blank">Notus JS</a> by <a href="https://www.creative-tim.com" class="text-blueGray-500 hover:text-blueGray-800" target="_blank"> Creative Tim</a>.
          </div>
        </div>
      </div>
    </div>
  </footer>
</section>